# Generated by Django 5.0.14 on 2026-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(default='ACCIONES', max_length=50, verbose_name='Mercado')),
                ('origen', models.CharField(default='CORREDOR', max_length=50, verbose_name='Origen')),
                ('periodo_comercial', models.IntegerField(default=2025, verbose_name='Periodo Comercial')),
                ('ejercicio', models.CharField(max_length=20, verbose_name='Ejercicio')),
                ('instrumento', models.CharField(max_length=100, verbose_name='Instrumento')),
                ('fecha_pago', models.DateField(verbose_name='Fecha Pago')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('secuencia_evento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secuencia Evento')),
            ],
        ),
    ]
