# Generated by Django 5.0.14 on 2026-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0002_calificaciontributaria_factor_08_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='acogido_isfut',
            field=models.BooleanField(default=False, verbose_name='Acogido ISFUT'),
        ),
    ]
